export * from './AudioIcon';
export * from './CloudUploadIcon';
export * from './DeleteIcon';
export * from './ExcelIcon';
export * from './PDFIcon';
export * from './PPTIcon';
export * from './TXTIcon';
export * from './WordIcon';
export * from './HelpSquareIcon';